services:
  backend:
    build: ./app
    ports:
      - "8080:8080"
    volumes:
      - ./app/traffic.db:/app/traffic.db

  frontend:
    build: ./traffic-ui
    ports:
      - "3000:3000"
    depends_on:
      - backend